site_name: Liaoxuefeng Java Tutorial
site_url: https://happy-mei.github.io/liaoxuefeng-en/site/
site_description: 廖雪峰的 Java 教程 英文版。An unofficial English translation of Liaoxuefeng's Java Tutorial, for educational purposes only.
site_author: happy-mei
copyright: >
  © 2023 happy-mei. This is an unofficial, non-commercial translation of 廖雪峰的 Java 教程.
  All original content © 廖雪峰. Visit the official tutorial at https://liaoxuefeng.com/books/java.

theme:
  name: material
  logo: assets/images/favicon-32x32.png
  favicon: assets/images/favicon-16x16.png
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  # - Home: index.md
  - 1 Introduction: 10-introduction/README.md
  - 2 Quick Start:
      - Overview: 20-quick-start/README.md
      - 2.1 Java History: 20-quick-start/10-history/README.md
      - 2.2 Development Env:
          - Overview: 20-quick-start/20-dev-env/README.md
          - 2.2.1 Install JDK: 20-quick-start/20-dev-env/10-install-jdk/README.md
          - 2.2.2 First Program: 20-quick-start/20-dev-env/20-first-program/README.md
          - 2.2.3 IDE Setup: 20-quick-start/20-dev-env/30-ide/README.md
      - 2.3 Basic Syntax:
          - Overview: 20-quick-start/30-basic/README.md
          - 2.3.1 Program Structure: 20-quick-start/30-basic/10-program-structure/README.md
          - 2.3.2 Variables and Types: 20-quick-start/30-basic/20-var-type/README.md
          - 2.3.3 Integer Types: 20-quick-start/30-basic/30-integer/README.md
          - 2.3.4 Floating Point Types: 20-quick-start/30-basic/40-float/README.md
          - 2.3.5 Boolean Type: 20-quick-start/30-basic/50-boolean/README.md
          - 2.3.6 String Type: 20-quick-start/30-basic/60-string/README.md
          - 2.3.7 Arrays: 20-quick-start/30-basic/70-array/README.md
      - 2.4 Flow Control:
          - Overview: 20-quick-start/40-flow/README.md
          - 2.4.1 Input & Output: 20-quick-start/40-flow/10-input-output/README.md
          - 2.4.2 If Statement: 20-quick-start/40-flow/20-if/README.md
          - 2.4.3 Switch Statement: 20-quick-start/40-flow/30-switch/README.md
          - 2.4.4 While Loop: 20-quick-start/40-flow/40-while/README.md
          - 2.4.5 Do-While Loop: 20-quick-start/40-flow/50-do-while/README.md
          - 2.4.6 For Loop: 20-quick-start/40-flow/60-for/README.md
          - 2.4.7 Break and Continue: 20-quick-start/40-flow/70-break-continue/README.md
      - 2.5 Array Operations:
          - Overview: 20-quick-start/50-array-op/README.md
          - 2.5.1 Looping Arrays: 20-quick-start/50-array-op/10-loop/README.md
          - 2.5.2 Sorting Arrays: 20-quick-start/50-array-op/20-sort/README.md
          - 2.5.3 Multidimensional Arrays: 20-quick-start/50-array-op/30-multi-dim/README.md
          - 2.5.4 Command Line Arguments: 20-quick-start/50-array-op/40-args/README.md
  - 3 OOP:
    - 3.1 OOP Basic:
        - Overview: 30-oop/10-basic/README.md
        - 3.1.1 Method: 30-oop/10-basic/10-method/README.md
        - 3.1.2 Constructor: 30-oop/10-basic/20-constructor/README.md
        - 3.1.3 Overload: 30-oop/10-basic/30-overload/README.md
        - 3.1.4 Inherit: 30-oop/10-basic/40-inherit/README.md
        - 3.1.5 Polymorphic: 30-oop/10-basic/50-polymorphic/README.md
        - 3.1.6 Abstract Class: 30-oop/10-basic/60-abstract-class/README.md
        - 3.1.7 Interface: 30-oop/10-basic/70-interface/README.md
        - 3.1.8 Static: 30-oop/10-basic/80-static/README.md
        - 3.1.9 Package: 30-oop/10-basic/90-package/README.md
        - 3.1.10 Scope: 30-oop/10-basic/100-scope/README.md
        - 3.1.11 Inner Class: 30-oop/10-basic/110-inner-class/README.md
        - 3.1.12 Classpath & JAR: 30-oop/10-basic/120-classpath-jar/README.md
        - 3.1.13 Class Version: 30-oop/10-basic/130-class-version/README.md
        - 3.1.14 Module: 30-oop/10-basic/140-module/README.md
    - 3.2 Java Core Classes:
        - Overview: 30-oop/20-core/README.md
        - 3.2.1 String Encoding: 30-oop/20-core/10-string-encoding/README.md
        - 3.2.2 StringBuilder: 30-oop/20-core/20-string-builder/README.md
        - 3.2.3 StringJoiner: 30-oop/20-core/30-string-joiner/README.md
        - 3.2.4 Wrapper: 30-oop/20-core/40-wrapper/README.md
        - 3.2.5 JavaBean: 30-oop/20-core/50-javabean/README.md
        - 3.2.6 Enum: 30-oop/20-core/60-enum/README.md
        - 3.2.7 Record: 30-oop/20-core/70-record/README.md
        - 3.2.8 BigInteger: 30-oop/20-core/80-biginteger/README.md
        - 3.2.9 BigDecimal: 30-oop/20-core/90-bigdecimal/README.md
        - 3.2.10 Utils: 30-oop/20-core/100-utils/README.md
  - 4 Exception Handling:
      - Overview: 40-exception/README.md
      - 4.1 Java Exception Basics: 40-exception/10-java-exception/README.md
      - 4.2 Catching Exceptions: 40-exception/20-catch-exception/README.md
      - 4.3 Throwing Exceptions: 40-exception/30-throw-exception/README.md
      - 4.4 Custom Exceptions: 40-exception/40-custom-exception/README.md
      - 4.5 NullPointerException: 40-exception/50-null-pointer-exception/README.md
      - 4.6 Assertions: 40-exception/60-assert/README.md
      - 4.7 JDK Logging: 40-exception/70-jdk-logging/README.md
      - 4.8 Commons Logging: 40-exception/80-commons-logging/README.md
      - 4.9 Log4j: 40-exception/90-log4j/README.md
      - 4.10 SLF4J and Logback: 40-exception/100-slf4j-logback/README.md

