site_name: Liaoxuefeng Java Tutorial-廖雪峰Java教程英文翻译

site_url: https://happy-mei.github.io/liaoxuefeng-en/site/

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  # - Home: index.md
  - Introduction: 10-introduction/README.md
  - Quick Start:
    - Overview: 20-quick-start/README.md
    - Java History: 20-quick-start/10-history/README.md
    - Development Environment:
      - Overview: 20-quick-start/20-dev-env/README.md
      - Install JDK: 20-quick-start/20-dev-env/10-install-jdk/README.md
      - First Program: 20-quick-start/20-dev-env/20-first-program/README.md
      - IDE Setup: 20-quick-start/20-dev-env/30-ide/README.md
    - Basic Syntax:
      - Overview: 20-quick-start/30-basic/README.md
      - Program Structure: 20-quick-start/30-basic/10-program-structure/README.md
      - Variables and Types: 20-quick-start/30-basic/20-var-type/README.md
      - Integer Types: 20-quick-start/30-basic/30-integer/README.md
      - Floating Point Types: 20-quick-start/30-basic/40-float/README.md
      - Boolean Type: 20-quick-start/30-basic/50-boolean/README.md
      - String Type: 20-quick-start/30-basic/60-string/README.md
      - Arrays: 20-quick-start/30-basic/70-array/README.md
    - Flow Control:
      - Overview: 20-quick-start/40-flow/README.md
      - Input & Output: 20-quick-start/40-flow/10-input-output/README.md
      - If Statement: 20-quick-start/40-flow/20-if/README.md
      - Switch Statement: 20-quick-start/40-flow/30-switch/README.md
      - While Loop: 20-quick-start/40-flow/40-while/README.md
      - Do-While Loop: 20-quick-start/40-flow/50-do-while/README.md
      - For Loop: 20-quick-start/40-flow/60-for/README.md
      - Break and Continue: 20-quick-start/40-flow/70-break-continue/README.md
    - Array Operations:
      - Overview: 20-quick-start/50-array-op/README.md
      - Looping Arrays: 20-quick-start/50-array-op/10-loop/README.md
      - Sorting Arrays: 20-quick-start/50-array-op/20-sort/README.md
      - Multidimensional Arrays: 20-quick-start/50-array-op/30-multi-dim/README.md
      - Command Line Arguments: 20-quick-start/50-array-op/40-args/README.md
  - OOP:
    - Basic:
        - Overview: 30-oop/10-basic/README.md
        - Method: 30-oop/10-basic/10-method/README.md
        - Constructor: 30-oop/10-basic/20-constructor/README.md
        - Overload: 30-oop/10-basic/30-overload/README.md
        - Inherit: 30-oop/10-basic/40-inherit/README.md
        - Polymorphic: 30-oop/10-basic/50-polymorphic/README.md
        - Abstract Class: 30-oop/10-basic/60-abstract-class/README.md
        - Interface: 30-oop/10-basic/70-interface/README.md
        - Static: 30-oop/10-basic/80-static/README.md
        - Package: 30-oop/10-basic/90-package/README.md
        - Scope: 30-oop/10-basic/100-scope/README.md
        - Inner Class: 30-oop/10-basic/110-inner-class/README.md
        - Classpath & JAR: 30-oop/10-basic/120-classpath-jar/README.md
        - Class Version: 30-oop/10-basic/130-class-version/README.md
        - Module: 30-oop/10-basic/140-module/README.md
    - Core:
        - Overview: 30-oop/20-core/README.md
        - String Encoding: 30-oop/20-core/10-string-encoding/README.md
        - StringBuilder: 30-oop/20-core/20-string-builder/README.md
        - StringJoiner: 30-oop/20-core/30-string-joiner/README.md
        - Wrapper: 30-oop/20-core/40-wrapper/README.md
        - JavaBean: 30-oop/20-core/50-javabean/README.md
        - Enum: 30-oop/20-core/60-enum/README.md
        - Record: 30-oop/20-core/70-record/README.md
        - BigInteger: 30-oop/20-core/80-biginteger/README.md
        - BigDecimal: 30-oop/20-core/90-bigdecimal/README.md
        - Utils: 30-oop/20-core/100-utils/README.md
  - Exception Handling:
    - Overview: 40-exception/README.md
    - Java Exception Basics: 40-exception/10-java-exception/README.md
    - Catching Exceptions: 40-exception/20-catch-exception/README.md
    - Throwing Exceptions: 40-exception/30-throw-exception/README.md
    - Custom Exceptions: 40-exception/40-custom-exception/README.md
    - NullPointerException: 40-exception/50-null-pointer-exception/README.md
    - Assertions (`assert`): 40-exception/60-assert/README.md
    - JDK Logging: 40-exception/70-jdk-logging/README.md
    - Commons Logging: 40-exception/80-commons-logging/README.md
    - Log4j: 40-exception/90-log4j/README.md
    - SLF4J and Logback: 40-exception/100-slf4j-logback/README.md
